previews:
  generation: automatic # Enable preview environments

services:
- type: web
  name: yfinance-mcp
  runtime: docker
  repo: https://github.com/thapar25/yfinance-mcp
  plan: free
  region: oregon
  healthCheckPath: /health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"